### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by rbozan** [hs-CN/msedge-tts#1]
Hi, is there a way to get proxy support in this crate? So I can proxy the Websocket requests through my proxy?

**Comment by hs-CN** [comment]
hi, thanks for the issue. I've read the documentation for **isahc** and **tungstenite**. **isahc** support `http_proxy`, `https_proxy` and `socks4/5` proxy, so `get_voice_list` can easily support all proxy types. 
**Tungstenite** doesn't seem to have such support [#177](https://github.com/snapview/tungstenite-rs/issues/177) The good thing is that Tungstenite allows us to use our own TCP/TLS stream, and I might be able to establish a proxy connection before starting the websocket handshake.
But it's going to be a busy time starting tomorrow when we have Chinese New Year, so I'll deal with that in a few days.

**Comment by hs-CN** [comment]
fixed on #2 .
