### ISSUE TITLE
Suggestion for code enhancement, and integration simplification

### ISSUE THREAD

**Issue by icsboyx** [hs-CN/msedge-tts#4]
Dear, 
Is it possible for you to derive Clone for:
struct Voice and dependency 

derive Clone and serde::Deserialize, serde::Serialize
struct SpeechConfig

Thanks
ics

**Comment by hs-CN** [comment]
ok, fixed on #5 and new version 0.2.4 has been release

**Comment by icsboyx** [comment]
Thank you so much !!
